# Generated by Django 2.1.3 on 2018-12-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20181211_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='SectorEconomico',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Profesional Independiente'), (2, 'Comerciante'), (3, 'Industrial'), (4, 'Agropecuario'), (5, 'Empleado Asalariado'), (6, 'Otro')]),
        ),
    ]
