# Generated by Django 2.1.3 on 2018-12-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20181211_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Nacionalidad',
            field=models.CharField(choices=[('PY', 'Paraguayo'), ('BR', 'Brasilero')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TipoDireccion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Residencia'), (2, 'Laboral'), (3, 'Comercial'), (4, 'Fiscal')]),
        ),
    ]
