# Generated by Django 2.1.3 on 2018-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20181211_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CargoTrabajo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ComprobanteIngreso',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Dependiente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NO'), (2, 'SI')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='EstadoCivil',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Casado'), (2, 'Soltero'), (3, 'Concubinato'), (4, 'Divorciado'), (5, 'Viudo'), (6, 'Sin datos')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='FechaNacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Genero',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Salario',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
