# Generated by Django 2.1.3 on 2018-12-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20181211_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Bario',
            new_name='Barrio',
        ),
    ]
